name: dart_self_driving_car
description: Self driving car.
version: 1.0.0

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
